README.md, styles/buttons.less, styles/tabs.less, styles/ui-variables.less
Until or maybe even as an alternative to #9, this PR imports the Syntax variables and changes the UI based on the syntax background color. This makes it more flexible to use with other than the matching One dark Syntax theme.
Test theme (unpublished)
Atom
Monokai
Hannah
If you pick a light Syntax theme, the UI stays dark but still uses its hue. Here the Sepia theme:
=> Use Syntax colors

styles/packages.less, styles/tabs.less, styles/ui-variables.less
This styles the `markdown-preview` package so it matches the theme colors.
Before:
After:
=> markdown-preview

styles/ui-variables.less
This PR adds some color guards. Fixes #22 
It limits saturation more for __brown/green__ colors, but keeps it the same strong for __blue/purple__. Below an example with `One dark` + `Printen`.
Before:
After:
In other words.. make it look less like :hankey: and more like :chocolate_bar:.
---
Also in case a Syntax theme is very dark (like Atom dark), the UI flips around to be lighter than the Syntax background. So that there is still a noticeable difference.
Before:
After:
=> Saturation guards

styles/buttons.less
Buttons with `.btn-success` were showing with gray icons instead of white. This should make every icon match the text color.
e.g. package updating in the settings view:
Now:
=> Ensure button icons have the right text color

styles/tabs.less, styles/ui-variables.less
In some cases the label in the tabs "shake". See #27
This PR removes the `opacity` on the tab and move the background to an own pseudo element. This might help with the above issue.
=> Move tab background to its own layer

styles/atom.less, styles/badges.less, styles/buttons.less, styles/core.less, styles/editor.less, styles/key-binding.less, styles/lists.less, styles/modal.less, styles/packages.less, styles/panes.less, styles/settings.less, styles/status-bar.less, styles/tabs.less, styles/tooltips.less, styles/tree-view.less, styles/ui-variables.less
This PR adds `px` units to the `ui-variables`, but still keeps using `em`s internally. In other words..
- This will give packages that use the `ui-variables` a fixed size and be more predictable.
- The core UI and bundled packages can still be scaled from styles.less.
Fixes: #37, https://github.com/atom/deprecation-cop/issues/34
=> Use px in ui-variables

styles/key-binding.less, styles/tooltips.less
All three font declarations in this theme were written differently: one with double quotes, one with single quotes and one with none. Using the declaration in `ui-variables.less` as a base, I changed the other two to use single quotes for consistency. It's the little things. :smiley:
=> :art: Make font values more consistent

index.less, lib/config.coffee, lib/settings.coffee, package.json, styles/config.less, styles/core.less, styles/tree-view.less, styles/ui-variables.less
This PR adds 3 layout modes that can be changed in the settings. Closes #40
- `spacious`. Like the current "framed" version, but with `12px` font size (instead of `11px`).
- `compact`. More compact with `11px` font size. Looks close to pre `0.6.0`.
- `auto`. This is the default. It automatically switches between the spacious and compact mode based on how large the window is. It also switches to `13px` and `14px` font size the wider the window gets.
ps. It's still possible to override the font size in `styles.less`, no matter what layout mode is chosen. So you could have compact mode with a very large `16px` font size if preferred. Or spacious mode with a small font size.
=> Layout Modes

styles/tabs.less
This PR adds some improvements to the tabs. Closes #49 
- Let's you see at least icon + 4 characters
- Close icon is only visible on hover.
- Active tab stays the same width.
- Increases the max width a bit.
- All tabs have the same width. Should allow the "delaying tab size" feature for quick succession closing.
- Replaces the ellipsis with a fade out. This lets you see an extra 2-3 characters.
=> Improve tabs

styles/ui-variables.less
This PR tries to address these issue: #45, #47 and #68.
- Solarized Dark and Monokai don't invert the colors, only if the syntax background is very dark (`<10%).
- If there is no saturation (black/grey), the accent color is blue instead of red.
- Blue-ish saturations are capped only for very dark backgrounds.
Solarized Dark before:
Solarized Dark after:
=> Normalize colors

lib/config.coffee, lib/settings.coffee
This PR adds a font size setting. Closes #62
- If set, it will override the font sizes in the Layout Modes.
- It's still possible to change individual areas in styles.less, like `.tab-bar { font-size: 14px; }`.
=> Font Size setting

styles/tabs.less
Allow other "Editor"s to match the special dynamic table styling that's currently given to data-type=TextEditor.
https://discuss.atom.io/t/how-to-make-my-tabs-look-like-texteditor-tabs-in-the-new-one-themes/14995/4
=> Allow all "Editors" to get dynamic tab styling.

package.json, styles/ui-variables.less
Refs https://github.com/atom/atom/pull/8778
This PR re-specifies a `@font-family`, but this time using the new `system` keyword.
=> Use system font (more robustly)

styles/packages.less, styles/tabs.less, styles/ui-variables.less
The Markdown Preview package will adapt to themes. See PR https://github.com/atom/markdown-preview/pull/298
So no more overriding is needed here. :sparkles:
=> Remove Markdown Preview styling

styles/tabs.less
The bottom border was cut off in the center.
Before
After
Fixes https://github.com/atom/one-dark-ui/issues/106
=> Fix tab bottom border

styles/progress.less
Before:
After:
Benefits:
- Doesn't need repaints, uses HWA layers
- Colors match better the theme. Especially the white gif was was hard to see in One light.
- The gif looked a bit pixelated
Although R.I.P. :octocat: :cry:
=> Replace spinner

styles/key-binding.less, styles/tooltips.less
This PR removes the hardcoded `font-family` in keybindings.
Closes https://github.com/atom/one-dark-ui/issues/99
=> Remove hardcoded fonts

styles/buttons.less
:warning:  This depends on this PR in core: https://github.com/atom/atom/pull/9480
This PR centers the icons in buttons. Fixes https://github.com/atom/one-dark-ui/issues/103
Before:
After:
=> Center icons in buttons

styles/config.less, styles/tree-view.less
... so that it doesn't overlap with anything added to the top.
Fixes point `2` of https://github.com/atom/atom/pull/9274#issuecomment-162856053
=> Keep tree-view marker relative positioned

package.json, styles/tree-view.less
With very long lines the texts would stop rendering after a certain point.
Before:
I did some trawling through the history and found that commit 25de9953d150b2a4c11631f5669955d349edfb66 caused the issue.
I'm not quite sure what the transform is for. So I may be breaking a use case I'm unaware of
After:
=> Remove transform that was preventing text from rendering

styles/modal.less
Same as https://github.com/atom/atom/pull/10782 in core, but a custom fix since this theme uses `em`s.
=> Shrink modals when window gets narrow

styles/config.less
This PR makes the tabs only use the width they need when in "compact mode".
- closes #120
- closes #94
=> Use auto-size for tabs in compact mode

styles/config.less, styles/tree-view.less
Now that the status-bar spans full-width, it's not clear where the tree-view ends.
Ref: https://github.com/atom/one-light-ui/issues/55
=> Add tree-view bottom border

styles/config.less
Before :see_no_evil: | After :monkey_face:
--- | ---
This also makes the dot and close-icon a bit less wide, to minimize accidental clicks.
Fixes https://github.com/atom/one-light-ui/issues/59
=> Add mask to modified dot

styles/config.less, styles/tabs.less, styles/ui-variables.less
This came up in https://github.com/atom/atom/issues/11448. The clickable area will become smaller, but you see exactly where it starts/ends.
Before :heavy_multiplication_x: | After :negative_squared_cross_mark:
--- | ---
=> Add background to close icon

styles/buttons.less, styles/editor.less, styles/progress.less, styles/settings.less, styles/tabs.less, styles/tree-view.less, styles/ui-mixins.less, styles/ui-variables-custom.less, styles/ui-variables.less
This refactors some styles around the "accent color".
Additionally, the accent color gets also used for:
- For the install buttons in the settings. So it matches the "Update all" button.
- The checkboxes
=> Accent color

styles/config.less
This makes the "Auto mode" breakpoint a bit smaller. From `1280x800` to `1000x600`.
So in "Auto mode", if the window is:
Smaller or `1000x600` | Larger than `1000x600`
--- | ---
Compact layout | Spacious layout
Minimal tabs | Even tabs
Closes #149
=> Reduce Auto breakpoints

styles/atom.less, styles/config.less, styles/panels.less, styles/panes.less
So that packages don't have to care about adding borders or padding. Plus a few more tweaks related to panes and panels.
Before | After
--- | ---
Fixes #159
=> Fix pane and panel border

styles/config.less, styles/panes.less
New approach: This time, using the `atom-pane-resize-handle` to add some spacing between panes.
Ref: https://github.com/atom/one-dark-ui/issues/159#issuecomment-244270220
=> Fix padding (take 2)

styles/lists.less
This is the same change as atom/one-light-ui#73, but for the Dark UI theme.
=> List group: maintain consistent size regardless of active icon presence

styles/text.less, styles/tree-view.less, styles/ui-variables-custom.less, styles/ui-variables.less
Having semi-transparent background colors causes issues when used on a light background.
Before | After
--- | ---
=> Remove transparency

styles/buttons.less, styles/inputs.less, styles/settings.less, styles/tabs.less, styles/ui-variables-custom.less, styles/ui-variables.less
This changes a bit how the accent color gets used.
There are now two accent colors:
- one for larger UI elements like button, tooltip.. 
- and one for smaller elements, like the active pane marker or inputs.
Ref: https://github.com/atom/one-dark-ui/issues/156
=> Accent color adjustments

styles/editor.less
So they don't grow too large. Currently limited at 5 rows:
Closes https://github.com/atom/one-dark-ui/issues/166
=> Add max height to mini editors

index.less, styles/core.less, styles/notifications.less
So it can be changed in the theme settings.
Closes https://github.com/atom/one-dark-ui/issues/170
=> Make notifications have a flexible font-size

styles/packages.less
Note: It doesn't work if the syntax theme has a red or green-ish background. Because then it would be hard to tell the states apart. 
Closes https://github.com/atom/one-dark-ui/issues/150
=> Colorize find-and-replace based on results

styles/ui-variables-custom.less
Before | After
--- | ---
This is specially tweaked for the "Atom Material Syntax" theme.
/cc @Ben3eeE
=> Shift contrast of accent text color

styles/key-binding.less, styles/packages.less, styles/ui-variables-custom.less
Same as: https://github.com/atom/one-light-ui/pull/87
=> Colorize character matches in the command palette

styles/packages.less
This adjusts the button widths of find-and-replace.
Makes them a bit smaller and saves some space.
Change is needed because of https://github.com/atom/find-and-replace/pull/840
=> Adjust find-and-replace button widths

styles/tabs.less
This makes sure the the element with the `data-path` attribute receives mouse events (instead of the pseudo-element), allowing us to target `[data-path]` in context menu items.
The corresponding PR for the light theme is atom/one-light-ui#94
=> Make sure [data-path] element receives mouse events

styles/tabs.less
This is a small update that goes along with atom/atom#13977 and changes the color of the active tab.
=> Style tabs in docks differently

styles/config.less, styles/docks.less
This goes with atom/atom#14178, which makes collapsed docks take up no space.
=> Remove dock min size

styles/status-bar.less, styles/ui-variables-custom.less
This replaces the underlines in the Status Bar with highlighting the background on hover.
Before | After
--- | ---
More like a button with rounded corners:
Might look nicer, but makes the click target smaller.
Makes all clicky things more consistent. Underlines should only be used for **external links**.
As mentioned here https://github.com/atom/status-bar/issues/196#issuecomment-311899047, there isn't a convention/API around Status Bar tiles. So it currently adds a hover effect on **all** `inline-block`s and resets a few bundled packages. But there is a chance that some community packages don't use that class. Also if a tile isn't clickable, package could add the `is-read-only`, but that's undocumented and only used by this theme.
Would be great to extend the API to add the same class to …
=> Status Bar hover effect

styles/tree-view.less
This vertically centers the arrow icon in the tree-view.
- We could fix it in the tree-view package, but it's not broken for all themes.
- It's not pixel perfect (off by `1px`), but it still adapts to different font sizes.
More visually pleasing.
Before | After
--- | ---
- One theme forks still have this issue.
Fixes https://github.com/atom/tree-view/issues/1163
Related https://github.com/atom/one-light-ui/pull/105
=> Center tree-view arrow icon

styles/tree-view.less
This PR centers the `>` arrow icon of the project root by using the same font-size as the label.
Centered icon
With larger font sizes, the arrow icon might get too close to the folder icon.
Fixes #222
=> Center project root icon

styles/tree-view.less, styles/ui-variables-custom.less
This replaces the blue "stripe" indicator with a background for the selected item when the tree-view gets focus.
Before | After
--- | ---
It's more consistent with the GitHub package and also Atom IDE UI.
- A downside is that when the selected item gets scrolled out of sight, you can't tell anymore that the tree-view has focus.
- Another one: The colors might clash when files are modified/added.
Based on: https://github.com/atom/one-dark-ui/issues/52#issuecomment-333024501
=> Replace tree-view focus indicator

styles/tabs.less, styles/ui-variables-custom.less
Fades VCS colored tabs that are not active.
Instead of using color for VCS, there could be modified/added icons. Or other indicators. But they would need extra space.
Makes the active tab stand out more.
Decreases contrast and some people might like to have modified/added tabs be stronger.
Closes #226
=> Fade VCS colored non-active tabs

styles/inputs.less, styles/packages.less, styles/ui-mixins.less
Styles invalid inputs.
Makes it more consistent with the find+replace inputs.
None
Closes #225
=> Style invalid inputs

styles/docks.less
This PR adjust the dock toggle button position.
Removes the `1px` gap introduced in https://github.com/atom/atom/pull/16414
None
https://github.com/atom/atom/pull/16414
=> Fix dock toggle button position

styles/modal.less
Fixes the focus border from being cut off.
Before | After
--- | ---
Easier on the 👀 
None
=> Fix command palette input border

lib/main.coffee, package.json, spec/theme-spec.coffee
This changes the font size picker to a dropdown instead of a text input.
Add a longer delay when typing a number.
Fixes the following problem with a text input:
1. if you are at `11` and want to go to `12`, you hit delete and it goes to `1`.
2. Because `1` is too small, it automatically changes to `8` (the minimum font size).
3. Then you type `2`. Which is now `82`. But since that is over the maximum, it changes to `20`.
Not as quick as a text input to change to a different number.
Ref https://github.com/atom/one-light-ui/issues/47
=> Use dropdown as font size picker

styles/tree-view.less
Same as https://github.com/atom/one-light-ui/pull/121
=> Sticky projects

styles/tabs.less
After you install and disable the welcome plug and enable one-dark-ui > hide dock toggle button, the activity indicator of the tab disappears.
=> Fix tabs.less

lib/main.coffee, package.json, spec/theme-spec.coffee, styles/config.less, styles/tree-view.less
Add config setting to enable/disable sticky tree-view headers (Default is enabled)
User can opt out of sticky tree-view headers
none
#249
=> Sticky header config

styles/config.less
This fixes the sticky headers from covering auto-revealed items in the tree-view. See this comment for more details: https://github.com/atom/one-dark-ui/pull/246#issuecomment-376458967
Use JS to change the scroll position. But better to keep it theme only.
Item is visible when auto-revealed
There could be side effects.
This is a follow-up fix for #246.
=> Fix sticky header from covering auto-revealed items

styles/ui-variables-custom.less
This adds more contrast to the scrollbar thumb.
Before | After
--- | ---
Easier to see
Too strong.
Closes #241
=> Increase contrast of scrollbar thumb

lib/main.coffee, package.json, spec/theme-spec.coffee, styles/config.less
This adds a config option to move the close buttons shown in tabs to the ⬅️ **left**.
More familiar for people that are used to have them on the left, like in native apps on macOS.
Maintenance cost.
Closes #202
=> Add option for left tab close buttons
