- index.less
- styles/atom.less
- styles/badges.less
- styles/buttons.less
- styles/core.less
- styles/key-binding.less
- styles/lists.less
- styles/modal.less
- styles/packages.less
- styles/panels.less
- styles/settings.less
- styles/status-bar.less
- styles/tabs.less
- styles/tooltips.less
- styles/tree-view.less
- styles/ui-variables.less
See https://github.com/atom/one-light-ui/pull/10 for more details. This is the same also for One dark.
> Variable font size

- styles/atom.less
- styles/panels.less
- styles/panes.less
- styles/status-bar.less
- styles/tabs.less
- styles/tree-view.less
- styles/ui-variables.less
This PR adds some visual tweaks. Mainly..
- Some padding on the top and right side. A little space is lost, but frames the editor and makes it stand out more.
- Rounded tabs. Also, the text doesn't jump when switching between only a few tabs.
> Framed editor

- styles/ui-variables.less
Fixes #26 + #17
Before:
After:
> Increase text contrast

- styles/ui-variables.less
This theme looks lovely with SF font.
> Add SF UI Text

- styles/ui-variables.less
See https://github.com/atom/atom/pull/8612
> Use San Francisco font on El Capitan Beta

- styles/ui-variables.less
Depends on https://github.com/atom/atom/pull/8778
Refs https://github.com/atom/atom/issues/8656
/cc @simurai @atom/feedback
> Use system default font

- styles/packages.less
:warning: This PR is dependant on https://github.com/atom/find-and-replace/pull/509. Only merge this if that PR gets merged.
> Increase project-find button blocks

- styles/ui-variables.less
"Blue" and "green" should be swapped (am I an achromate?).
> Fix comments for @ui-site-color-s

- styles/ui-variables.less
New pull request resulting from #119.
> Fix typo in comment for ui-variables.less

- lib/main.coffee
- package.json
- spec/theme-spec.coffee
- styles/config.less
Adds config for tab sizing (even vs minimum). I wrote tests but was not sure how to run them. I ran coffeelint.
> Add config for tab sizing

- package.json
This came up in https://github.com/atom/atom/issues/4342#issuecomment-222338390.
> Clarify what Font Size: Auto does

- styles/core.less
Now that it’s fixed in the Styleguide package
> Remove some Styleguide overrides

- index.less
- styles/inputs.less
So that it matches syntax colors.
> Use accent color for the inputs

- styles/config.less
- styles/core.less
- styles/panes.less
This will fix the `atom-pane-resize-handle` position. Part of https://github.com/atom/atom/pull/12300
> Fix pane resize handle

- styles/config.less
- styles/panels.less
a.k.a. remove borders on the side, to improve scrolling.
Closes https://github.com/atom/atom/issues/12998
> Add infinite edge

- styles/modal.less
- styles/ui-variables-custom.less
So it doesn't interfere with the traffic lights.
Before | After
--- | ---
Closes https://github.com/atom/one-dark-ui/issues/165
> Move modal down

- styles/tabs.less
> Hide tab-bar when empty

- styles/messages.less
> Restyle background tips

- styles/ui-variables-custom.less
> Improve selection in mini editors

- styles/buttons.less
- styles/editor.less
- styles/inputs.less
Same as https://github.com/atom/one-light-ui/pull/95
> Improve focus

- package.json
- spec/theme-spec.coffee
- styles/config.less
- styles/tabs.less
Same as https://github.com/atom/one-light-ui/pull/97.
> Add maximum tab option

- styles/tabs.less
Same as https://github.com/atom/one-light-ui/pull/100
> Adjust tab icon size

- styles/buttons.less
- styles/status-bar.less
- styles/tabs.less
Same as https://github.com/atom/one-light-ui/pull/105
> Align icons

- styles/status-bar.less
Same as https://github.com/atom/one-light-ui/pull/108
> Vertically center sync icon

- styles/status-bar.less
Same as https://github.com/atom/one-light-ui/pull/112
> Add hover effect to status-bar-cursor

- styles/tree-view.less
Same as https://github.com/atom/one-light-ui/pull/117
> Increase contrast of VCS colored and focused tree-view

- styles/packages.less
- styles/ui-variables.less
Same as https://github.com/atom/one-light-ui/pull/131
> Change overlay background color

- styles/config.less
Same as https://github.com/atom/one-light-ui/pull/133
> More sticky header fixes

- styles/status-bar.less
Same as https://github.com/atom/one-light-ui/pull/135
> Remove status-bar underline

- styles/lists.less
Same as https://github.com/atom/one-light-ui/pull/141
> Reset icons in select lists
